
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const GET_SNIPPETS_REQUEST = 'GET_SNIPPETS_REQUEST'
export const GET_SNIPPETS_SUCCESS = 'GET_SNIPPETS_SUCCESS'
export const GET_SNIPPETS_FAIL = 'GET_SNIPPETS_FAIL'

export const GET_SNIPPET_REQUEST = 'GET_SNIPPET_REQUEST'
export const GET_SNIPPET_SUCCESS = 'GET_SNIPPET_SUCCESS'
export const GET_SNIPPET_FAIL = 'GET_SNIPPET_FAIL'

export const CREATE_SNIPPET_REQUEST = 'CREATE_SNIPPET_REQUEST'
export const CREATE_SNIPPET_SUCCESS = 'CREATE_SNIPPET_SUCCESS'
export const CREATE_SNIPPET_FAIL = 'CREATE_SNIPPET_FAIL'

export const DELETE_SNIPPET_REQUEST = 'DELETE_SNIPPET_REQUEST'
export const DELETE_SNIPPET_SUCCESS = 'DELETE_SNIPPET_SUCCESS'
export const DELETE_SNIPPET_FAIL = 'DELETE_SNIPPET_FAIL'

export const SET_UPDATE_SNIPPET = 'SET_UPDATE_SNIPPET'
export const UPDATE_SNIPPET_REQUEST = 'UPDATE_SNIPPET_REQUEST'
export const UPDATE_SNIPPET_SUCCESS = 'UPDATE_SNIPPET_SUCCESS'
export const UPDATE_SNIPPET_FAIL = 'UPDATE_SNIPPET_FAIL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SETUP_USER_REQUEST = 'SETUP_USER_REQUEST'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_FAIL = 'SETUP_USER_FAIL'

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'